name: sample-01

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
# 빌드 작업
  job-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: dev
      url: https://www.sample-01.com
    env:
      SAMPLE_VALUE: sampleValue
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: echo env value
      run: echo ${{env.SAMPLE_VALUE}}/${{secrets.SAMPLE_SECRET_NAME}}/${{vars.SAMPLE_VAR_NAME}}

    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10"

    - run: chmod +x ./gradlew
    
    - name: Gradle build
      run: ./gradlew build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: git-actions-test-jar
        path: build/libs
    
    - name: Set Debug
      id: set-debug-stage
      run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

    - run: echo $GITHUB_OUTPUT
    - run: cat $GITHUB_OUTPUT

    - name: Get Stage
      run: echo "${{steps.set-debug-stage.outputs.BUILD_STAGE}}"

# 테스트 작업
  job-test:
    runs-on: ubuntu-latest
    needs: job-build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: git-actions-test-jar

      - run: java -version
      
      - shell: sh
        run: |
          java -jar git-actions-test-0.0.1-SNAPSHOT.jar
    # - name: GH Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: v0.0.1
    #     token: ${{secrets.GITHUB_TOKEN}}
    #     generate_release_notes: true
    #     name: Dev
    #     files: README.md
