name: sample-01

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: dev
      url: https://www.sample-01.com
    env:
      SAMPLE_VALUE: sampleValue
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: echo env value
      run: echo ${{env.SAMPLE_VALUE}}/${{secrets.SAMPLE_SECRET_NAME}}/${{vars.SAMPLE_VAR_NAME}}

    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10"

    - run: chmod +x ./gradlew
    
    - name: Gradle build
      run: ./gradlew build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: archive.zip
        path: build/libs

    - name: GH Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.0.1
        generat/e_release_notes: true
        name: Dev
        # files: archive.zip
